apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devchebackend
  name: devchebackend
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devchebackend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devchebackend
    spec:
      containers:
      - image: scinet0786/devchefrontend:latest
        name: devchebackend
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: devchebackendservice
  namespace: microservice
spec:
  selector:
    app: devchebackend
    protocol: TCP
  ports:
  - port: 8080
  type: LoadBalancer

