apiVersion: v1
kind: Service
metadata:
  name: devchebackendservice
  namespace: microservice
spec:
  selector:
    app: devchebackend
    protocol: TCP
  ports:
  - port: 8080
  type: LoadBalancer


