apiVersion: v1
kind: Namespace
metadata:
  name: microservice
---


apiVersion: apps/v1
kind: Deployment
metadata:
   name: devche
   labels:
      app: frontend
   namespace: microservice
spec:
  replicas: 2
  matchlabels:
    app: frontend
  template:
    metadata:
      matchlabels:
        app: frontend
    spec:
        containers:
          - image: scinet0786/devchefrontend:latest
            name: devchefrontend
            ports:
              containerPort: 8081
            env:
              - name: PORT_NUMBER
                valueFrom:
                  ConfigMapKeyRef:
                    name: portnumberCM
                    key: port_no

---
apiVersion: v1
kind: service
metadata:
  name: devchefrontendservice
  namesapce: microservice
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
      app: frontend
    protocol: TCP
  type: LoadBalancer